Repository CherryHQ/cherry-studio, pull requests merged in 2025-09, with the labels that each got.

#9633 feat(MCPSettings): add special error boundary & data validation for mcp server
  src/renderer/src/components/Popups/GeneralPopup.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/MCPSettings/AddMcpServerModal.tsx
  src/renderer/src/pages/settings/MCPSettings/EditMcpJsonPopup.tsx
  src/renderer/src/pages/settings/MCPSettings/McpServerCard.tsx
  src/renderer/src/pages/settings/MCPSettings/index.tsx
  src/renderer/src/types/index.ts
  src/renderer/src/types/mcp.ts
  src/renderer/src/utils/__tests__/error.test.ts
  src/renderer/src/utils/error.ts
  src/renderer/src/utils/json.ts
Labels: needs-review

#10191 fix: ui package env
  .oxlintrc.json
  .vscode/settings.json
Labels: v2

#10237 refactor: migrate Switch from antd to heroui
  eslint.config.mjs
  packages/ui/src/components/base/Switch/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/utils/index.ts
  src/renderer/src/components/Buttons/ActionIconButton.tsx
  src/renderer/src/components/ObsidianExportDialog.tsx
  src/renderer/src/context/HeroUIProvider.tsx
  src/renderer/src/hero.ts
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/minapps/MiniappSettings/MiniAppSettings.tsx
  src/renderer/src/pages/paintings/AihubmixPage.tsx
  src/renderer/src/pages/paintings/DmxapiPage.tsx
  src/renderer/src/pages/paintings/SiliconPage.tsx
  src/renderer/src/pages/paintings/components/DynamicFormRender.tsx
  src/renderer/src/pages/settings/AboutSettings.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantMCPSettings.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantMemorySettings.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
  src/renderer/src/pages/settings/DataSettings/ExportMenuSettings.tsx
  src/renderer/src/pages/settings/DataSettings/JoplinSettings.tsx
  src/renderer/src/pages/settings/DataSettings/LocalBackupSettings.tsx
  src/renderer/src/pages/settings/DataSettings/MarkdownExportSettings.tsx
  src/renderer/src/pages/settings/DataSettings/NotionSettings.tsx
  src/renderer/src/pages/settings/DataSettings/NutstoreSettings.tsx
  src/renderer/src/pages/settings/DataSettings/S3Settings.tsx
  src/renderer/src/pages/settings/DataSettings/WebDavSettings.tsx
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
  src/renderer/src/pages/settings/GeneralSettings.tsx
  src/renderer/src/pages/settings/MCPSettings/McpServerCard.tsx
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
  src/renderer/src/pages/settings/MCPSettings/McpTool.tsx
  src/renderer/src/pages/settings/MemorySettings/MemorySettings.tsx
  src/renderer/src/pages/settings/ModelSettings/DefaultAssistantSettings.tsx
  src/renderer/src/pages/settings/ModelSettings/QuickModelPopup.tsx
  src/renderer/src/pages/settings/NotesSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/ApiOptionsSettings/ApiOptionsSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/EditModelPopup/ModelEditContent.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/pages/settings/QuickAssistantSettings.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/SelectionAssistantSettings.tsx
  src/renderer/src/pages/settings/ShortcutSettings.tsx
  src/renderer/src/pages/settings/WebSearchSettings/BasicSettings.tsx
  src/renderer/src/pages/settings/index.tsx
  src/renderer/src/pages/translate/TranslateSettings.tsx
  src/renderer/src/windows/dataRefactorTest/components/PreferenceBasicTests.tsx
Labels: v2

#10403 feat: add GitHub Copilot CLI integration to coding tools
  packages/shared/config/constant.ts
  src/main/services/CodeToolsService.ts
  src/renderer/src/hooks/useCodeTools.ts
  src/renderer/src/pages/code/CodeToolsPage.tsx
  src/renderer/src/pages/code/index.ts
  src/renderer/src/store/codeTools.ts
Labels: PM said OK
