Repository CherryHQ/cherry-studio, pull requests merged in 2025-05, with the labels that each got.

#5469 feat(OpenAIProvider): support image edit
  package.json
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/FileStorage.ts
  src/preload/index.ts
  src/renderer/src/components/Icons/SvgSpinners180Ring.tsx
  src/renderer/src/components/MinApp/MinappPopupContainer.tsx
  src/renderer/src/pages/home/Inputbar/AttachmentButton.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/Blocks/ImageBlock.tsx
  src/renderer/src/pages/home/Messages/Blocks/PlaceholderBlock.tsx
  src/renderer/src/pages/home/Messages/MessageImage.tsx
  src/renderer/src/pages/home/Messages/MessageTranslate.tsx
  src/renderer/src/pages/home/Messages/Messages.tsx
  src/renderer/src/pages/home/components/Suggestions.tsx
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/services/FileManager.ts
  yarn.lock
Labels: kind/feature, sig/LLM

#5577 perf: improve inputbar button memorization
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/KnowledgeBaseButton.tsx
  src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
  src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
Labels: area/Performance

#5565 fix(mcp-tools): improve error message formatting and response handlin…
  src/renderer/src/utils/mcp-tools.ts
Labels: sig/MCP

#5567 refactor: enhance image block rendering and styling
  src/renderer/src/pages/home/Messages/Blocks/index.tsx
  src/renderer/src/pages/home/Messages/MessageImage.tsx
Labels: area/UI/UX, kind/cleanup

#5533 Feat/qwen3 support
  src/renderer/src/components/Icons/SVGIcon.tsx
  src/renderer/src/config/models.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/locales/zh/translation.json
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/ThinkingButton.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/types/index.ts
Labels: area/UI/UX, kind/feature, sig/LLM

#5592 feat: implement store synchronization across windows
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/StoreSyncService.ts
  src/main/services/WindowService.ts
  src/preload/index.ts
  src/renderer/src/init.ts
  src/renderer/src/services/StoreSyncService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/settings.ts
  src/renderer/src/types/index.ts
  src/renderer/src/windows/mini/entryPoint.tsx
  src/renderer/src/windows/mini/home/HomeWindow.tsx
Labels: kind/feature

#5580 perf(inputbar): improve long text paste
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: area/Performance

#5596 refactor: simplify custom CSS functionality by store sync
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/ConfigManager.ts
  src/preload/index.ts
  src/renderer/src/hooks/useAppInit.ts
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
  src/renderer/src/services/StoreSyncService.ts
  src/renderer/src/windows/mini/MiniWindowApp.tsx
Labels: kind/cleanup

#5595 fix(Anthropic): add base64 file handling to IPC and file management
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/FileStorage.ts
  src/preload/index.ts
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/services/FileManager.ts
Labels: sig/LLM

#5619 fix: resolve scrolling issue on files page (#5618)
  src/renderer/src/pages/files/FileList.tsx
Labels: area/UI/UX

#5606 Remove redundant condition check in MCP service args handling
  src/main/services/MCPService.ts
Labels: lgtm, kind/cleanup

#5641 feat(messageOperations): add editMessageBlocks functionality and upda…
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/pages/home/Messages/ChatFlowHistory.tsx
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Messages/Messages.tsx
  src/renderer/src/store/newMessage.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/windows/mini/chat/components/Messages.tsx
Labels: kind/feature

#5589 refactor(WindowService): improve context menu setup
  src/main/services/ContextMenu.ts
  src/main/services/WindowService.ts
Labels: area/UI/UX, kind/cleanup

#5633 refactor(WindowService, ThemeProvider): streamline title bar style and theme toggling logic
  src/main/config.ts
  src/main/services/WindowService.ts
  src/renderer/src/components/app/Navbar.tsx
Labels: area/UI/UX, kind/cleanup

#5650 chore(dependencies): update electron-updater to version 6.6.4 and remove patches
  .yarn/patches/electron-updater-npm-6.6.3-9269dbaf84.patch
  package.json
  yarn.lock
Labels: kind/cleanup

#5654 fix: remove redundant local variables
  src/main/mcpServers/brave-search.ts
  src/main/mcpServers/fetch.ts
  src/main/mcpServers/filesystem.ts
  src/main/mcpServers/sequentialthinking.ts
  src/main/services/ExportService.ts
  src/main/services/GeminiService.ts
  src/main/services/MCPService.ts
  src/main/services/NutstoreService.ts
  src/main/services/ProxyManager.ts
  src/main/services/SearchService.ts
  src/main/services/mcp/oauth/callback.ts
  src/main/utils/zip.ts
Labels: kind/cleanup

#5540 feat: 支持自定义助手地址
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/pages/agents/AgentsPage.tsx
  src/renderer/src/pages/agents/components/ImportAgentPopup.tsx
  src/renderer/src/pages/agents/index.ts
  src/renderer/src/store/settings.ts
Labels: sig/Assistant, kind/feature

#5658 Fix/image height
  src/renderer/src/pages/home/Messages/Blocks/index.tsx
  src/renderer/src/pages/home/Messages/MessageImage.tsx
Labels: area/UI/UX

#5670 fix: conditionally show loading more spinner
  src/renderer/src/pages/home/Messages/Messages.tsx
Labels: area/UI/UX

#5660 feat: popup question editor support translation assistant
  src/renderer/src/components/Popups/TextEditPopup.tsx
  src/renderer/src/utils/__tests__/index.test.ts
Labels: area/UI/UX, lgtm, kind/feature

#5671 fix: infinite scroller layout
  src/renderer/src/pages/home/Messages/Messages.tsx
Labels: area/UI/UX

#5673 refactor: add Linux support for margin adjustments in MinappPopupConainer and McpSettingsNavbar
  src/renderer/src/components/MinApp/MinappPopupContainer.tsx
  src/renderer/src/context/ThemeProvider.tsx
  src/renderer/src/pages/settings/MCPSettings/McpSettingsNavbar.tsx
Labels: sig/MCP, area/UI/UX, kind/cleanup

#5621 feat(OpenAI): new Responses API support
  src/renderer/src/config/models.ts
  src/renderer/src/pages/settings/ProviderSettings/AddProviderPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/AiProvider/ProviderFactory.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/messageBlock.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/mcp-tools.ts
Labels: kind/feature, sig/LLM

#5696 feat: emit event on message complete
  src/renderer/src/services/EventService.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: kind/feature

#5717 feat(WebSearchButton): add 'Disable Web Search' option
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
Labels: area/UI/UX, kind/feature

#5722 优化消息块渲染性能，使用 useMemo 缓存图像块组；移除调试日志以清理代码
  src/renderer/src/pages/home/Messages/Blocks/index.tsx
  src/renderer/src/providers/AiProvider/index.ts
  src/renderer/src/services/ApiService.ts
  src/renderer/src/services/StreamProcessingService.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/utils/queue.ts
Labels: kind/cleanup, area/Performance

#5725 feat: support dashscope reranker
  src/main/reranker/DashscopeReranker.ts
  src/main/reranker/RerankerFactory.ts
  src/renderer/src/config/providers.ts
Labels: kind/feature

#5682 fix: chat message translate
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: needs-review

#5516 feat: change citation list style
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Markdown/Markdown.tsx
  src/renderer/src/pages/home/Messages/CitationsList.tsx
  src/renderer/src/windows/mini/chat/components/Messages.tsx
Labels: area/UI/UX, lgtm

#5707 feat: optimize knowledge recognize
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/AssistantSettings/AssistantKnowledgeBaseSettings.tsx
  src/renderer/src/services/ApiService.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/extract.ts
Labels: sig/RAG, kind/feature

#5637 refactor(middleware): add extractReasoningMiddleware for enhanced text processing
  src/renderer/src/middlewares/extractReasoningMiddleware.ts
  src/renderer/src/providers/AiProvider/BaseProvider.ts
  src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
  src/renderer/src/utils/formats.ts
  src/renderer/src/utils/getPotentialIndex.ts
  src/renderer/src/utils/stream.ts
Labels: kind/cleanup, sig/LLM

#5742 fix: citation list loading
  package.json
  src/renderer/src/pages/home/Messages/ChatFlowHistory.tsx
  src/renderer/src/pages/home/Messages/CitationsList.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/store/messageBlock.ts
  yarn.lock
Labels: area/Performance

#5665 feat: add zoom factor setting and localization support
  packages/shared/IpcChannel.ts
  packages/shared/config/constant.ts
  src/main/ipc.ts
  src/main/services/ShortcutService.ts
  src/preload/index.ts
  src/renderer/src/hooks/useAppInit.ts
  src/renderer/src/hooks/useSettings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature

#5740 chore: remove unuseful doc
  src/renderer/src/locales/zh/translation.json
Labels: kind/cleanup

#5739 feat[MCP]: implement login shell environment retrieval
  src/main/services/MCPService.ts
  src/main/services/mcp/shell-env.ts
Labels: sig/MCP, kind/feature

#5751 feat(MCP): update auto-install server name and add server registratio…
  src/renderer/src/store/migrate.ts
  src/renderer/src/utils/mcp-tools.ts
Labels: sig/MCP, kind/feature

#5752 fix(theme): citation list dark theme display & url repeatedly requesting
  package.json
  src/renderer/src/pages/home/Messages/CitationsList.tsx
  yarn.lock
Labels: area/UI/UX

#5763 Feat: change Gemini Safety Settings to OFF; upgrade @google/genai package
  package.json
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  yarn.lock
Labels: kind/feature, sig/LLM

#5769 fix(MCP): Revise the server type judgment logic to ensure the correct…
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: sig/MCP

#5731 feat: Custom mini app
  packages/shared/IpcChannel.ts
  scripts/check-i18n.js
  src/main/ipc.ts
  src/main/services/FileStorage.ts
  src/preload/index.ts
  src/renderer/src/assets/images/apps/application.png
  src/renderer/src/components/Popups/MinAppsPopover.tsx
  src/renderer/src/config/minapps.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/apps/App.tsx
  src/renderer/src/pages/apps/AppsPage.tsx
  src/renderer/src/pages/settings/MiniappSettings/MiniAppSettings.tsx
  src/renderer/src/types/index.ts
Labels: area/UI/UX, kind/feature

#5674 refactor(ModelList): improve model list style and grouping
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/AddModelPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
  src/renderer/src/utils/__tests__/naming.test.ts
  src/renderer/src/utils/naming.ts
Labels: area/UI/UX, lgtm

#5776 feat(minapps): add n8n mini app with logo and URL.
  src/renderer/src/assets/images/apps/n8n.ico
  src/renderer/src/config/minapps.ts
Labels: kind/feature

#5780 fix: display image from mcp response
  src/renderer/src/utils/mcp-tools.ts
Labels: sig/MCP

#5758 feat: tooluse result display style optimization
  src/renderer/src/pages/home/Messages/MessageTools.tsx
  src/renderer/src/utils/shiki.ts
Labels: area/UI/UX, kind/feature

#5773 fix: remove useless border and border radius for code block
  src/renderer/src/pages/home/Markdown/CodeBlock.tsx
Labels: area/UI/UX

#5594 perf: virtual list for quick panel and SelectModelPopup
  package.json
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/components/CustomTag.tsx
  src/renderer/src/components/ModelTagsWithLabel.tsx
  src/renderer/src/components/Popups/SelectModelPopup.tsx
  src/renderer/src/components/QuickPanel/provider.tsx
  src/renderer/src/components/QuickPanel/view.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  yarn.lock
Labels: area/Performance

#5789 feat: add the "Export Agent" feature
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/agents/components/AgentCard.tsx
Labels: area/UI/UX, kind/feature

#5795 fix: SelectModelPopup sticky header
  src/renderer/src/components/Popups/SelectModelPopup.tsx
Labels: area/UI/UX

#5499 feat: support both function call and system prompt for MCP tools
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/MessageTools.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  src/renderer/src/providers/AiProvider/AihubmixProvider.ts
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/BaseProvider.ts
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/services/AssistantService.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/mcp-tools.ts
  src/renderer/src/utils/prompt.ts
Labels: sig/MCP, area/UI/UX, kind/feature

#5818 feat: combine to general reranker
  src/main/reranker/BaseReranker.ts
  src/main/reranker/DashscopeReranker.ts
  src/main/reranker/DefaultReranker.ts
  src/main/reranker/GeneralReranker.ts
  src/main/reranker/JinaReranker.ts
  src/main/reranker/Reranker.ts
  src/main/reranker/RerankerFactory.ts
  src/main/reranker/SiliconFlowReranker.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
  src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
Labels: kind/feature

#5812 fix: SelectModelPopup scrolling behaviour
  src/renderer/src/components/Popups/SelectModelPopup/hook.ts
  src/renderer/src/components/Popups/SelectModelPopup/index.ts
  src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
  src/renderer/src/components/Popups/SelectModelPopup/reducer.ts
  src/renderer/src/components/Popups/SelectModelPopup/types.ts
  src/renderer/src/hooks/usePinnedModels.ts
Labels: area/UI/UX, kind/cleanup

#5608 feat(webSearch): add Bocha web search provider integration
  src/renderer/src/assets/images/search/bocha.webp
  src/renderer/src/config/webSearchProviders.ts
  src/renderer/src/pages/settings/WebSearchSettings/WebSearchProviderSetting.tsx
  src/renderer/src/providers/WebSearchProvider/BaseWebSearchProvider.ts
  src/renderer/src/providers/WebSearchProvider/BochaProvider.ts
  src/renderer/src/providers/WebSearchProvider/ExaProvider.ts
  src/renderer/src/providers/WebSearchProvider/SearxngProvider.ts
  src/renderer/src/providers/WebSearchProvider/TavilyProvider.ts
  src/renderer/src/providers/WebSearchProvider/WebSearchProviderFactory.ts
  src/renderer/src/services/ApiService.ts
  src/renderer/src/services/WebSearchService.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/websearch.ts
  src/renderer/src/types/bocha.ts
Labels: area/UI/UX, kind/feature

#5824 docs(README): add Architecture overview document
  README.md
Labels: kind/documentation

#5819 fix: update selectedTypes logic in ModelEditContent for better handling
  src/renderer/src/config/models.ts
  src/renderer/src/pages/settings/ProviderSettings/ModelEditContent.tsx
Labels: kind/cleanup

#5439 feat: add prompt display control
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/Messages.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
Labels: size:S

#5775 feat: Agent Regular Phrases
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/agents/components/ImportAgentPopup.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/QuickPhrasesButton.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantRegularPromptsSettings.tsx
  src/renderer/src/pages/settings/AssistantSettings/index.tsx
  src/renderer/src/services/AssistantService.ts
  src/renderer/src/types/index.ts
Labels: sig/Assistant, kind/feature

#5836 feat: regularPhrases可以随Agent一起导出。
  src/renderer/src/pages/agents/components/AgentCard.tsx
Labels: kind/feature

#5840 feat(i18n): 更新机器翻译多语言，使用Qwen3 236b进行机器翻译。
  scripts/update-i18n.ts
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
Labels: area/UI/UX, kind/feature

#5851 fix: clean up code
  scripts/notarize.js
  src/main/mcpServers/dify-knowledge.ts
  src/main/services/ProtocolClient.ts
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/WebSearchProvider/index.ts
  src/renderer/src/utils/api.ts
  src/renderer/src/utils/blacklistMatchPattern.ts
  src/renderer/src/utils/messageUtils/create.ts
  src/renderer/src/utils/messageUtils/filters.ts
  src/renderer/src/utils/queue.ts
Labels: kind/cleanup

#5860 fix: conditionally aquire focus for inputbar
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: area/UI/UX

#5857 refactor(checkAPI): check api or model with stream enabled first
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/services/ApiService.ts
  src/renderer/src/services/HealthCheckService.ts
  src/renderer/src/services/ModelService.ts
Labels: kind/cleanup

#5684 feat: add message translate copy & close
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/utils/messageUtils/find.ts
Labels: needs-review, area/UI/UX, kind/feature

#5866 fix(Inputbar): do not reset selection on focus
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: area/UI/UX

#5869 feat: add motion library for animations and enhance Spinner and Messa…
  package.json
  src/renderer/src/components/Spinner.tsx
  src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
  src/renderer/src/pages/home/Messages/Blocks/index.tsx
  yarn.lock
Labels: area/UI/UX, kind/feature

#5880 docs: Improve the README for better readability
  README.md
Labels: kind/documentation

#5885 chore(workflows): update workflows for new repo structure
  .github/workflows/nightly-build.yml
  .github/workflows/pr-ci.yml
  .github/workflows/release.yml
Labels: area/CI/CD

#5891 feat(i18n): add page zoom settings in English, Japanese, and Russian …
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
Labels: area/UI/UX, kind/feature

#5895 chore: remove bufferutil dependency from package.json and yarn.lock
  package.json
  yarn.lock
Labels: kind/cleanup

#5905 feat: minimize token usage when testing model
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Labels: kind/feature, sig/LLM

#5919 feat(knowledge): adjust default top-n to 10
  src/main/reranker/BaseReranker.ts
  src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
Labels: kind/feature

#5855 refactor: SelectModelPopup pinning
  src/renderer/src/components/CustomTag.tsx
  src/renderer/src/components/ModelTagsWithLabel.tsx
  src/renderer/src/components/Popups/SelectModelPopup/hook.ts
  src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
  src/renderer/src/components/Popups/SelectModelPopup/reducer.ts
  src/renderer/src/components/Popups/SelectModelPopup/types.ts
Labels: area/UI/UX, kind/cleanup

#5821 feat: add undo functionality to agent prompt generation
  src/renderer/src/pages/agents/components/AddAgentPopup.tsx
Labels: area/UI/UX, kind/feature

#5915 fix(ipc): enhance theme handling with title bar overlay updates and broadcast notifications
  src/main/ipc.ts
Labels: area/UI/UX

#5928 revert: openai compatible type
  src/renderer/src/config/models.ts
  src/renderer/src/databases/upgrades.ts
  src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
  src/renderer/src/pages/settings/ProviderSettings/AddProviderPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/providers/AiProvider/AihubmixProvider.ts
  src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
  src/renderer/src/providers/AiProvider/ProviderFactory.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/messageBlock.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
Labels: sig/LLM

#5943 feature: Hide disabled options for web search
  src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
Labels: area/UI/UX, kind/feature

#5944 docs: Add Photo instructions to the branch strategy document
  docs/branching-strategy.md
Labels: kind/documentation

#5938 feat: Optimize the display method for the three modes
  src/renderer/src/pages/home/Messages/MessageTokens.tsx
Labels: area/UI/UX, kind/feature

#5947 fix: animation on resolving SelectModelPopup
  src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
Labels: area/UI/UX

#5946 chore: use node-stream-zip to improve perfermanc and remove unused dependencies
  package.json
  src/main/services/BackupManager.ts
  yarn.lock
Labels: kind/cleanup, area/Performance

#5932 refactor: improve model management UI, add animations to some buttons
  src/renderer/src/components/ExpandableText.tsx
  src/renderer/src/components/ModelIdWithTags.tsx
  src/renderer/src/components/ModelTags.tsx
  src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
  src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelListSearchBar.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/utils/motionVariants.ts
Labels: area/UI/UX, kind/cleanup, sig/LLM

#5954 添加智能体订阅功能
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/agents/index.ts
  src/renderer/src/pages/settings/DataSettings/AgentsSubscribeUrlSettings.tsx
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature

#5950 fix: quickpanel auto-scroll behaviour
  src/renderer/src/components/QuickPanel/types.ts
  src/renderer/src/components/QuickPanel/view.tsx
Labels: area/UI/UX

#5987 fix lint errors
  package.json
  src/main/services/BackupManager.ts
  src/renderer/src/pages/agents/components/AddAgentPopup.tsx
  src/renderer/src/pages/agents/index.ts
  src/renderer/src/pages/home/Messages/MessageTokens.tsx
Labels: kind/cleanup

#5963 feat: 更长上下文
  src/renderer/src/config/constant.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/TokenCount.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  src/renderer/src/services/AssistantService.ts
  src/renderer/src/services/EventService.ts
  src/renderer/src/services/MessagesService.ts
  src/renderer/src/types/index.ts
Labels: sig/Assistant, kind/feature

#5971 fix: enhance image block handling in message processing
  src/renderer/src/config/models.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: area/UI/UX

#5992 docs: 贡献者数据源
  README.md
Labels: kind/documentation

#6018 fix: Update Server McpSettings
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: sig/MCP, area/UI/UX

#6020 fix: remove undici dependency and clean up ProxyManager code
  package.json
  src/main/ipc.ts
  src/main/services/ProxyManager.ts
  src/main/utils/index.ts
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
  yarn.lock
Labels: kind/cleanup

#5151 feat: upgrade electron to 35.2.2
  .yarn/patches/app-builder-lib-npm-26.0.15-360e5b0476.patch
  electron-builder.yml
  package.json
  yarn.lock
Labels: client:win, lgtm, kind/feature, size:XS

#6058 fix: mcp params error(issues/6050)
  src/renderer/src/utils/mcp-tools.ts
Labels: sig/MCP, hotfix

#6064 禁止“自定义CSS”输入框的拼写检查
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
Labels: area/UI/UX

#6055 hotfix: openai websearch render and gemini think
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
Labels: hotfix

#6073 Hotfix/thinking time render
  src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
  src/renderer/src/store/thunk/messageThunk.ts
Labels: area/UI/UX

#6076 fix: Update the state of the last message block as a fallback
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: area/UI/UX

#6062 拓宽”请选择要检测的模型“模态框
  src/renderer/src/pages/settings/ProviderSettings/SelectProviderModelPopup.tsx
Labels: area/UI/UX

#6066 feat: add citation list right-click copy
  src/renderer/src/components/ContextMenu/index.tsx
  src/renderer/src/pages/home/Messages/CitationsList.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
Labels: area/UI/UX, kind/feature

#6071 refactor(CodeEditor): add more options to props for better customization, fix auto theme
  src/renderer/src/components/CodeEditor/index.tsx
  src/renderer/src/context/CodeStyleProvider.tsx
  src/renderer/src/pages/settings/MCPSettings/EditMcpJsonPopup.tsx
Labels: area/UI/UX, kind/cleanup

#6087 Fix: Update file API usage for Electron 35.2.2 and add translations f…
  src/preload/index.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/utils/input.ts
Labels: area/UI/UX

#6089 feat: Drop file improvements
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: area/UI/UX, kind/feature

#6092 chore: reduce package size
  package.json
  yarn.lock
Labels: kind/cleanup

#6000 feat: implement useFullscreen hook and integrate with NavbarRight for dynamic padding
  src/renderer/src/components/app/Navbar.tsx
  src/renderer/src/components/app/Sidebar.tsx
  src/renderer/src/hooks/useFullscreen.ts
  src/renderer/src/pages/settings/MCPSettings/McpSettingsNavbar.tsx
Labels: area/UI/UX, kind/feature

#3302 feat: Highlighted search in chat page
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/components/ContentSearch.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Chat.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/Messages.tsx
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/shortcuts.ts
Labels: area/UI/UX

#6079 fix: font-family changed in Windows with new Electron
  src/main/utils/windowUtil.ts
  src/renderer/src/assets/styles/color.scss
  src/renderer/src/assets/styles/font.scss
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/assets/styles/markdown.scss
  src/renderer/src/components/Layout/index.ts
  src/renderer/src/components/ListItem/index.tsx
  src/renderer/src/components/ModelIdWithTags.tsx
  src/renderer/src/components/QuickPanel/view.tsx
  src/renderer/src/config/constant.ts
  src/renderer/src/context/AntdProvider.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/TokenCount.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/MessageHeader.tsx
  src/renderer/src/pages/home/Tabs/AssistantItem.tsx
  src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/home/Tabs/index.tsx
  src/renderer/src/pages/knowledge/KnowledgePage.tsx
  src/renderer/src/pages/paintings/AihubmixPage.tsx
  src/renderer/src/pages/paintings/PaintingsPage.tsx
  src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/pages/settings/index.tsx
  src/renderer/src/windows/mini/chat/components/Message.tsx
Labels: area/UI/UX, kind/cleanup

#5948 chore: remove unused packages
  package.json
  yarn.lock
Labels: kind/cleanup

#6084 refactor: clean up code for `MessageGroupModelList`
  src/renderer/src/pages/home/Messages/MessageGroupModelList.tsx
Labels: kind/cleanup

#6019 feat: make sidebar setting group collapsible
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/settings/SettingGroup.tsx
Labels: area/UI/UX, kind/feature

#6122 Hotfix/rich text paste
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: hotfix

#6124 refactor(MessageGroup): optimize selected message handling with useMe…
  src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
Labels: kind/cleanup

#6103 fix: remove infinite token display for max count and simplify context count rendering.
  src/renderer/src/pages/home/Inputbar/TokenCount.tsx
Labels: area/UI/UX

#6128 hotfix: github models check error
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Labels: hotfix

#6127 refactor: streamline MCP service handling and improve IPC registration
  src/main/index.ts
  src/main/ipc.ts
  src/main/services/MCPService.ts
  src/main/services/WindowService.ts
  src/main/services/mcp/shell-env.ts
  src/renderer/src/hooks/useMCPServers.ts
  src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
Labels: sig/MCP, kind/cleanup, area/Performance

#6133 fix: Search results are on the right side
  src/renderer/src/components/ContentSearch.tsx
Labels: area/UI/UX

#6138 hotfix(i18n): Add multi-language support for network search settings
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
Labels: hotfix

#6136 feat: add buildFunctionCallToolName utility for generating tool names
  src/main/services/MCPService.ts
  src/main/utils/mcp.ts
Labels: kind/feature

#5793 feat: add MCP Run Python server and integrate Pyodide for executing P…
  package.json
  src/main/mcpServers/factory.ts
  src/main/mcpServers/mcp-run-python/main.ts
  src/main/mcpServers/mcp-run-python/polyfill.ts
  src/main/mcpServers/mcp-run-python/prepareEnvCode.ts
  src/main/mcpServers/mcp-run-python/runCode.ts
  src/renderer/src/store/mcp.ts
  yarn.lock
Labels: sig/MCP, kind/feature

#6143 fix: 多发消息时除fold布局以外的其他布局不能被渲染
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
Labels: area/UI/UX

#6140 refactor: serif messageFont & index.scss structure
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
  src/renderer/src/pages/home/Messages/MessageTools.tsx
Labels: kind/cleanup

#6121 refactor: transparent border for code blocks
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
  src/renderer/src/components/CodeEditor/index.tsx
Labels: area/UI/UX, kind/cleanup

#5852 feat: add FloatingSidebar component and integrate assistant switching…
  src/renderer/src/components/Popups/FloatingSidebar.tsx
  src/renderer/src/pages/home/HomePage.tsx
  src/renderer/src/pages/home/Navbar.tsx
  src/renderer/src/pages/home/Tabs/index.tsx
  src/renderer/src/services/EventService.ts
Labels: area/UI/UX, lgtm, kind/feature

#6152 refactor: improve sanitization and formatting in buildFunctionCallToo…
  src/main/utils/mcp.ts
Labels: kind/cleanup

#6156 refactor(messageThunk): optimize message update logic with atomic mod…
  src/renderer/src/store/thunk/messageThunk.ts
Labels: kind/cleanup

#5901 refactor: implement message editing and resend functionality
  src/renderer/__tests__/setup.ts
  src/renderer/src/context/MessageEditingContext.tsx
  src/renderer/src/hooks/useMCPServers.ts
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/pages/home/Inputbar/AttachmentPreview.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/MessageContent.tsx
  src/renderer/src/pages/home/Messages/MessageEditor.tsx
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/utils/messageUtils/find.ts
Labels: kind/feature, sig/LLM

#6169 feat: add zoom factor handling on window restore in WindowService
  src/main/services/WindowService.ts
Labels: area/UI/UX, kind/feature

#6173 Hotfix/gemini-para-bug
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
Labels: sig/LLM, hotfix

#6174 hotfix: respect user-defined model group name
  src/renderer/src/pages/settings/ProviderSettings/AddModelPopup.tsx
Labels: hotfix

#6164 feat(settings): add OpenAI alert
  src/renderer/src/components/Alert/OpenAIAlert.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
Labels: area/UI/UX, kind/feature, sig/LLM

#6150 feat: support default Quick Assistant model
  src/renderer/src/hooks/useAssistant.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
  src/renderer/src/store/llm.ts
  src/renderer/src/windows/mini/home/HomeWindow.tsx
Labels: kind/feature, sig/LLM

#5980 feat: add resolveFilePath functionality to resolve restoring from different computer
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/FileStorage.ts
  src/preload/index.ts
  src/renderer/src/services/BackupService.ts
  src/renderer/src/services/FileManager.ts
  src/renderer/src/services/KnowledgeService.ts
Labels: kind/feature

#6099 feat: add MCP servers via JSON quickly
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/MCPService.ts
  src/preload/index.ts
  src/renderer/src/components/CodeEditor/index.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/MCPSettings/AddMcpServerModal.tsx
  src/renderer/src/pages/settings/MCPSettings/EditMcpJsonPopup.tsx
  src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
Labels: sig/MCP, kind/feature

#6199 refactor: centralize paste handling logic with PasteService
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/MessageEditor.tsx
  src/renderer/src/services/PasteService.ts
Labels: area/UI/UX, kind/cleanup

#6175 feat: add new model provider BurnCloud
  src/renderer/src/assets/images/providers/burncloud.png
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
Labels: kind/feature, sig/LLM

#6165 fix(mcp): mcp result preview is missing parameters
  src/renderer/src/pages/home/Messages/MessageTools.tsx
Labels: sig/MCP

#6209 fix: knowledge icon consistency across components
  src/renderer/src/pages/settings/DisplaySettings/SidebarIconsManager.tsx
Labels: area/UI/UX

#6211 fix: add context menu trigger to FloatingSidebar component
  src/renderer/src/components/Popups/FloatingSidebar.tsx
Labels: area/UI/UX

#6151 Feat/mcp run python
  package.json
  src/main/mcpServers/factory.ts
  src/main/mcpServers/mcp-run-python/main.ts
  src/main/mcpServers/mcp-run-python/polyfill.ts
  src/main/mcpServers/mcp-run-python/prepareEnvCode.ts
  src/main/mcpServers/mcp-run-python/runCode.ts
  src/renderer/src/store/mcp.ts
  yarn.lock
Labels: sig/MCP, kind/feature

#6085 feat: add message multiple select
  .gitignore
  src/renderer/src/components/Popups/MultiSelectionPopup.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/history/components/SearchMessage.tsx
  src/renderer/src/pages/history/components/TopicMessages.tsx
  src/renderer/src/pages/home/Chat.tsx
  src/renderer/src/pages/home/Messages/ChatContext.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/MessageEditor.tsx
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Messages/MessageSelect.tsx
  src/renderer/src/pages/home/Messages/Messages.tsx
Labels: area/UI/UX, kind/feature

#6144 feat/notification
  package.json
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/NotificationService.ts
  src/preload/index.ts
  src/renderer/src/App.tsx
  src/renderer/src/config/models.ts
  src/renderer/src/context/NotificationProvider.tsx
  src/renderer/src/hooks/useUpdateHandler.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/GeneralSettings.tsx
  src/renderer/src/queue/KnowledgeQueue.ts
  src/renderer/src/queue/NotificationQueue.ts
  src/renderer/src/services/BackupService.ts
  src/renderer/src/services/NotificationService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/types/notification.ts
  src/renderer/src/utils/window.ts
  yarn.lock
Labels: area/UI/UX, kind/feature

#6257 fix: increase the upper limit of issue-management operations-per-run
  .github/workflows/issue-management.yml
Labels: area/CI/CD

#6235 refactor: reuse shiki highlighter utils
  package.json
  src/renderer/src/context/CodeStyleProvider.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/MessageTools.tsx
  src/renderer/src/pages/settings/MCPSettings/McpDescription.tsx
  src/renderer/src/services/ShikiStreamService.ts
  src/renderer/src/services/__tests__/ShikiStreamService.test.ts
  src/renderer/src/utils/asyncInitializer.ts
  src/renderer/src/utils/highlighter.ts
  src/renderer/src/utils/shiki.ts
  yarn.lock
Labels: kind/cleanup

#6271 refactor: enhance notification handling based on page
  src/renderer/src/context/NotificationProvider.tsx
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/utils/window.ts
Labels: area/UI/UX, kind/cleanup

#6266 fix: show x-scrollbar in codeblock if unwrapped, simplify style definitions
  src/renderer/src/assets/styles/markdown.scss
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
  src/renderer/src/components/CodeBlockView/index.tsx
  src/renderer/src/components/CodeEditor/index.tsx
  src/renderer/src/components/CodeToolbar/usePreviewTools.tsx
Labels: area/UI/UX

#6228 refactor: CodePreview fade in on the first highlighting
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
Labels: area/UI/UX

#6305 Fix: Use effective theme for code style in SettingsTab
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
Labels: area/UI/UX

#6299 feat: add functionality to insert messages at a specific index in the…
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
  src/renderer/src/store/newMessage.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: kind/feature

#6315 fix: handle empty block content in MessageTranslate component
  src/renderer/src/pages/home/Messages/MessageTranslate.tsx
Labels: area/UI/UX

#6321 feat: Grok Live Search Support
  src/renderer/src/config/models.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/store/messageBlock.ts
  src/renderer/src/types/index.ts
Labels: kind/feature

#6232 feat: toggle MCP servers on the card list
  src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
  src/renderer/src/utils/error.ts
Labels: sig/MCP, kind/feature

#6328 Support Claude 4
  src/renderer/src/config/models.ts
Labels: kind/feature, sig/LLM

#6323 feat: gemini thinking summary support
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
Labels: kind/feature, sig/LLM

#6191 feat: support pin topic to the top
  src/renderer/src/hooks/useSettings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature
