Repository CherryHQ/cherry-studio, pull requests merged in 2025-07, with the labels that each got.

#7699 fix(WindowService): remove backgroundThrottling option for improved window configuration
  src/main/services/WindowService.ts
Labels: area/Performance

#7673 feat(TopicsHistory): add sorting functionality for topics and update UI components
  src/renderer/src/pages/history/components/TopicsHistory.tsx
  src/renderer/src/store/assistants.ts
  src/renderer/src/store/thunk/messageThunk.ts
Labels: area/UI/UX, kind/feature

#7704 fix(WindowService): remove backgroundThrottling option for cleaner window configuration
  src/main/services/WindowService.ts
Labels: kind/cleanup

#7724 refactor(WebSearchMiddleware, linkConverter): enhance link processing and buffering logic
  src/renderer/src/aiCore/middleware/core/WebSearchMiddleware.ts
  src/renderer/src/utils/__tests__/linkConverter.test.ts
  src/renderer/src/utils/linkConverter.ts
Labels: kind/cleanup

#7623 fix: add custom prompt setting for translate model
  src/renderer/src/pages/translate/TranslatePage.tsx
Labels: area/UI/UX, kind/feature

#7717 PPIO OAuth Login
  src/renderer/src/components/OAuth/OAuthButton.tsx
  src/renderer/src/config/constant.ts
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/pages/settings/ProviderSettings/ProviderOAuth.tsx
  src/renderer/src/services/ProviderService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/utils/oauth.ts
Labels: area/UI/UX, kind/feature

#7744 chore: Disable auto-organize imports on save
  .vscode/settings.json
Labels: kind/cleanup

#7729 chore: update i18n script
  scripts/update-i18n.ts
Labels: kind/cleanup

#7529 refactor(ProviderSettings): add provider key by urlScheme
  electron-builder.yml
  src/main/index.ts
  src/main/services/ProtocolClient.ts
  src/main/services/urlschema/handle-providers.ts
  src/renderer/src/hooks/useProvider.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
Labels: area/UI/UX, kind/cleanup

#7740 feat: Add code linting plugin support to the Electron configuration
  electron.vite.config.ts
  package.json
  yarn.lock
Labels: kind/feature

#7743 chore: remove dependency updates
  .github/dependabot.yml
Labels: kind/cleanup

#7561 feat: SelectionAssistant macOS version / 划词助手macOS版
  electron-builder.yml
  package.json
  packages/shared/IpcChannel.ts
  src/main/configs/SelectionConfig.ts
  src/main/ipc.ts
  src/main/services/SelectionService.ts
  src/main/services/TrayService.ts
  src/preload/index.ts
  src/renderer/src/assets/styles/selection-toolbar.scss
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/SelectionAssistantSettings/SelectionAssistantSettings.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/MacProcessTrustHintModal.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/SelectionActionSearchModal.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/SelectionActionUserModal.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/SelectionActionsList.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/SelectionFilterListModal.tsx
  src/renderer/src/pages/settings/SelectionAssistantSettings/hooks/useSettingsActionsList.ts
  src/renderer/src/pages/settings/ShortcutSettings.tsx
  src/renderer/src/windows/selection/action/SelectionActionApp.tsx
  src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
  yarn.lock
Labels: needs-review, area/UI/UX, kind/feature

#7774 feat: add NewAPI provider
  src/renderer/src/aiCore/clients/ApiClientFactory.ts
  src/renderer/src/aiCore/clients/NewAPIClient.ts
  src/renderer/src/aiCore/index.ts
  src/renderer/src/assets/images/providers/newapi.png
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/hooks/useDynamicLabelWidth.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
  src/renderer/src/pages/knowledge/components/StatusIcon.tsx
  src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelEditContent.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
  src/renderer/src/pages/settings/ProviderSettings/NewApiAddModelPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/NewApiBatchAddModelPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/store/index.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
  src/renderer/src/types/sdk.ts
Labels: kind/feature, sig/LLM

#7803 feat(message-group): improve layout style
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
Labels: area/UI/UX

#7809 refactor(messageThunk): streamline loading state management for topics
  src/renderer/src/store/thunk/messageThunk.ts
Labels: kind/cleanup

#7811 feat(settings): add option to disable hardware acceleration
  packages/shared/IpcChannel.ts
  src/main/index.ts
  src/main/ipc.ts
  src/main/services/ConfigManager.ts
  src/preload/index.ts
  src/renderer/src/hooks/useSettings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/GeneralSettings.tsx
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature

#7797 fix: update websearch i18n, allow more search results
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/GithubCopilotSettings.tsx
  src/renderer/src/pages/settings/ToolSettings/WebSearchSettings/BasicSettings.tsx
  src/renderer/src/pages/settings/ToolSettings/WebSearchSettings/CompressionSettings/RagSettings.tsx
  src/renderer/src/services/WebSearchService.ts
Labels: sig/RAG, area/UI/UX

#7835 fix(CodePreview): line height rounding
  src/renderer/src/assets/styles/markdown.scss
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
Labels: area/UI/UX

#7789 fix(WindowService): update default window dimensions to improve user experience
  src/main/services/WindowService.ts
Labels: area/UI/UX

#7858 test: add comprehensive unit tests for asyncInitializer and copy utilities
  src/renderer/src/utils/__tests__/asyncInitializer.test.ts
  src/renderer/src/utils/__tests__/copy.test.ts
  src/renderer/src/utils/__tests__/export.test.ts
Labels: kind/test

#7856 fix: improve abortController robustness with defensive programming
  src/renderer/src/utils/__tests__/abortController.test.ts
  src/renderer/src/utils/abortController.ts
Labels: kind/cleanup, kind/test

#7868 fix(LMStudioSettings): prevent negative values in keepAliveMinutes input
  src/renderer/src/pages/settings/ProviderSettings/LMStudioSettings.tsx
Labels: area/UI/UX

#7869 fix(MCPSettings): ensure save button only restarts MCP server if it is running
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: area/UI/UX

#7888 chore: update readme badges
  README.md
Labels: kind/documentation

#7867 fix: hide scrollbars on capturing
  src/renderer/src/assets/styles/scrollbar.scss
  src/renderer/src/utils/image.ts
Labels: area/UI/UX

#7864 使自动更新版本号更健壮
  .github/workflows/dispatch-docs-update.yml
  .github/workflows/release.yml
Labels: area/CI/CD

#7896 chore: move ocr and preprocess into knowledge folder
  src/main/knowledage/ocr/BaseOcrProvider.ts
  src/main/knowledage/ocr/DefaultOcrProvider.ts
  src/main/knowledage/ocr/MacSysOcrProvider.ts
  src/main/knowledage/ocr/OcrProvider.ts
  src/main/knowledage/ocr/OcrProviderFactory.ts
  src/main/knowledage/preprocess/BasePreprocessProvider.ts
  src/main/knowledage/preprocess/DefaultPreprocessProvider.ts
  src/main/knowledage/preprocess/Doc2xPreprocessProvider.ts
  src/main/knowledage/preprocess/MineruPreprocessProvider.ts
  src/main/knowledage/preprocess/MistralPreprocessProvider.ts
  src/main/knowledage/preprocess/PreprocessProvider.ts
  src/main/knowledage/preprocess/PreprocessProviderFactory.ts
  src/main/services/KnowledgeService.ts
Labels: kind/cleanup

#7865 feat(mcp): Add default args for built-in file system MCP server
  src/renderer/src/store/mcp.ts
Labels: sig/MCP, kind/feature

#7784 feat(miniapp): add swap fo betterr filtering
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/apps/MiniappSettings/MiniAppSettings.tsx
Labels: area/UI/UX, kind/feature

#6353 feat: implement local cloud directory backup functionality
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/BackupManager.ts
  src/preload/index.ts
  src/renderer/src/components/LocalBackupManager.tsx
  src/renderer/src/components/LocalBackupModals.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/init.ts
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
  src/renderer/src/pages/settings/DataSettings/LocalBackupSettings.tsx
  src/renderer/src/services/BackupService.ts
  src/renderer/src/store/backup.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature

#7925 chore: git blame ignore
  .git-blame-ignore-revs
  package.json
Labels: kind/cleanup

#7904 perf: draggable virtual list
  src/renderer/src/components/DraggableList/index.tsx
  src/renderer/src/components/DraggableList/list.tsx
  src/renderer/src/components/DraggableList/virtual-list.tsx
  src/renderer/src/components/Scrollbar/index.tsx
  src/renderer/src/components/__tests__/DraggableList.test.tsx
  src/renderer/src/components/__tests__/DraggableVirtualList.test.tsx
  src/renderer/src/components/__tests__/__snapshots__/DraggableList.test.tsx.snap
  src/renderer/src/components/__tests__/__snapshots__/DraggableVirtualList.test.tsx.snap
  src/renderer/src/components/app/Sidebar.tsx
  src/renderer/src/pages/agents/components/ManageAgentsPopup.tsx
  src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/knowledge/KnowledgePage.tsx
  src/renderer/src/pages/paintings/components/PaintingsList.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantRegularPromptsSettings.tsx
  src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
  src/renderer/src/pages/settings/QuickPhraseSettings/index.tsx
Labels: needs-review, kind/feature, area/Performance

#7874 feat: provider custom header
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
Labels: kind/feature

#7842 refactor(CodePreview): smoothing code highlighting on streaming
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
Labels: area/UI/UX, kind/cleanup

#7905 feat: add painting support for NewAPI provider
  src/renderer/src/aiCore/clients/NewAPIClient.ts
  src/renderer/src/config/endpointTypes.ts
  src/renderer/src/hooks/usePaintings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/paintings/NewApiPage.tsx
  src/renderer/src/pages/paintings/PaintingsRoutePage.tsx
  src/renderer/src/pages/paintings/config/NewApiConfig.ts
  src/renderer/src/pages/settings/ProviderSettings/ModelEditContent.tsx
  src/renderer/src/pages/settings/ProviderSettings/NewApiAddModelPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/NewApiBatchAddModelPopup.tsx
  src/renderer/src/store/paintings.ts
  src/renderer/src/types/index.ts
Labels: area/UI/UX, kind/feature

#7953 revert: timing for adding citation references
  src/renderer/src/store/thunk/messageThunk.ts
Labels: kind/cleanup

#7950 fix: Improve model filtering and group handling
  src/renderer/src/config/models.ts
  src/renderer/src/pages/paintings/NewApiPage.tsx
  src/renderer/src/pages/paintings/config/NewApiConfig.ts
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
Labels: area/UI/UX, kind/cleanup

#7977 fix(LocalBackupSettings): update input and select styles for better responsiveness
  src/renderer/src/pages/settings/DataSettings/LocalBackupSettings.tsx
Labels: area/UI/UX

#7891 test: enhance download and fetch utility test coverage with bug fix
  src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
  src/renderer/src/utils/__tests__/download.test.ts
  src/renderer/src/utils/__tests__/fetch.test.ts
  src/renderer/src/utils/download.ts
Labels: kind/test

#8004 fix(SelectionAssistant): [macOS] show actionWindow on fullscreen app
  package.json
  src/main/services/SelectionService.ts
  src/preload/index.ts
  src/renderer/src/windows/selection/action/SelectionActionApp.tsx
  src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
  yarn.lock
Labels: needs-review

#8104 feat: enhance Anthropic and OpenAI API clients with incremental output support
  src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/types/sdk.ts
Labels: needs-review

#8116 perf: prevent unnecessary topic rerendering
  src/renderer/src/hooks/useTopic.ts
  src/renderer/src/pages/home/HomePage.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/home/Tabs/components/AssistantItem.tsx
Labels: needs-review

#8129 fix: serif font in markdown title styles
  src/renderer/src/assets/styles/markdown.scss
Labels: needs-review

#7931 Feat: url context for Gemini models
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/aiCore/clients/types.ts
  src/renderer/src/aiCore/middleware/core/ResponseTransformMiddleware.ts
  src/renderer/src/aiCore/middleware/schemas.ts
  src/renderer/src/config/tools.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/InputbarTools.tsx
  src/renderer/src/pages/home/Inputbar/UrlContextbutton.tsx
  src/renderer/src/services/ApiService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/inputTools.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
Labels: needs-review

#8157 fix(AihubmixAPIClient): enhance ID validation logic to exclude 'embed…
  src/renderer/src/aiCore/clients/AihubmixAPIClient.ts
Labels: needs-review

#8230 feat(minapp): add Google login tip for untrusted browser issue
  .vscode/launch.json
  src/renderer/src/components/MinApp/MinappPopupContainer.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
Labels: needs-review

#8302 Feature/dmxapi_painting_dynamic_model
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/paintings/DmxapiPage.tsx
  src/renderer/src/pages/paintings/config/DmxapiConfig.ts
  src/renderer/src/types/index.ts
Labels: needs-review

#8069 feat(CodeBlock): support matplotlib in code execution
  docs/technical/code-execution.md
  src/renderer/src/components/CodeBlockView/StatusBar.tsx
  src/renderer/src/components/CodeBlockView/view.tsx
  src/renderer/src/pages/home/Markdown/ImagePreview.tsx
  src/renderer/src/services/PyodideService.ts
  src/renderer/src/services/ShikiStreamService.ts
  src/renderer/src/workers/pyodide.worker.ts
Labels: needs-review, PM said OK

#7933 refactor: match provider and model using a consistent method
  README.md
  docs/technical/how-to-use-logger-en.md
  docs/technical/how-to-use-logger-zh.md
  src/renderer/src/components/ModelList/EditModelsPopup.tsx
  src/renderer/src/components/ModelList/ModelList.tsx
  src/renderer/src/components/ModelSelector.tsx
  src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
  src/renderer/src/components/__tests__/ModelSelector.test.tsx
  src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
  src/renderer/src/pages/home/Inputbar/MentionModelsInput.tsx
  src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
  src/renderer/src/pages/knowledge/components/KnowledgeSettings.tsx
  src/renderer/src/pages/memory/settings-modal.tsx
  src/renderer/src/pages/settings/MemorySettings/MemoriesSettingsModal.tsx
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/SelectProviderModelPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/pages/settings/ToolSettings/WebSearchSettings/CompressionSettings/RagSettings.tsx
  src/renderer/src/pages/settings/ToolSettings/WebSearchSettings/CompressionSettings/index.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
  src/renderer/src/services/ModelService.ts
  src/renderer/src/utils/__tests__/match.test.ts
  src/renderer/src/utils/index.ts
  src/renderer/src/utils/match.ts
Labels: needs-review

#7714 refactor: streamline system prompt handling and introduce built-in tools
  src/renderer/src/aiCore/clients/BaseApiClient.ts
  src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
  src/renderer/src/aiCore/middleware/core/McpToolChunkMiddleware.ts
  src/renderer/src/config/constant.ts
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/services/ApiService.ts
  src/renderer/src/store/thunk/messageThunk.ts
  src/renderer/src/tools/index.ts
  src/renderer/src/tools/think.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/__tests__/prompt.test.ts
  src/renderer/src/utils/mcp-tools.ts
  src/renderer/src/utils/prompt.ts
  src/renderer/traceWindow.html
Labels: needs-review

#8420 fix(ModelEdit): enhance model type management and introduce new selection logic
  src/renderer/src/components/ModelList/ModelEditContent.tsx
  src/renderer/src/config/models.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/__tests__/collection.test.ts
  src/renderer/src/utils/collection.ts
  src/renderer/src/utils/index.ts
Labels: needs-review

#8499 Feat/long run mcp
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/MCPService.ts
  src/preload/index.ts
  src/renderer/src/pages/home/Messages/MessageTools.tsx
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
  src/renderer/src/types/index.ts
Labels: PM said OK

#8440 feat(mcp): add shouldConfig flag and i18n support for builtin MCPServer description
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/MCPSettings/BuiltinMCPServersSection.tsx
  src/renderer/src/store/mcp.ts
  src/renderer/src/types/index.ts
Labels: Blocked

#8383 integrate AWS Bedrock API
  package.json
  src/renderer/src/aiCore/clients/ApiClientFactory.ts
  src/renderer/src/aiCore/clients/aws/AwsBedrockAPIClient.ts
  src/renderer/src/aiCore/middleware/core/StreamAdapterMiddleware.ts
  src/renderer/src/assets/images/providers/aws-bedrock.png
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/hooks/useAwsBedrock.ts
  src/renderer/src/i18n/label.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ProviderSettings/AwsBedrockSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
  src/renderer/src/types/sdk.ts
  src/renderer/src/utils/__tests__/aws-bedrock-utils.test.ts
  src/renderer/src/utils/aws-bedrock-utils.ts
  src/renderer/src/utils/mcp-tools.ts
  yarn.lock
Labels: needs-review, PM said OK
