Repository CherryHQ/cherry-studio, pull requests merged in 2025-06, with the labels that each got.

#6673 fix(OpenAIProvider): prevent atob error with non-base64 image URLs
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
Labels: sig/LLM

#6707 fix: replace franc with franc-min for improved performance
  package.json
  src/renderer/src/utils/translate.ts
  yarn.lock
Labels: area/Performance

#6702 feat(SelectionService): predefined filter list only available in Selected mode
  src/main/configs/SelectionConfig.ts
  src/main/services/SelectionService.ts
Labels: kind/feature

#6668 fix: adjust sidebar icon margins based on fullscreen state
  src/renderer/src/pages/home/Navbar.tsx
Labels: area/UI/UX

#6663 test: more unit tests for message rendering
  package.json
  src/renderer/src/components/__tests__/__snapshots__/Scrollbar.test.tsx.snap
  src/renderer/src/pages/home/Markdown/CitationTooltip.tsx
  src/renderer/src/pages/home/Markdown/__tests__/CitationTooltip.test.tsx
  src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
  src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/CitationTooltip.test.tsx.snap
  src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Markdown.test.tsx.snap
  src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
  src/renderer/src/pages/home/Messages/Blocks/__tests__/MainTextBlock.test.tsx
  src/renderer/src/pages/home/Messages/Blocks/__tests__/ThinkingBlock.test.tsx
  src/renderer/src/pages/home/Messages/Blocks/__tests__/__snapshots__/ThinkingBlock.test.tsx.snap
  src/renderer/src/utils/__tests__/formats.test.ts
  src/renderer/src/utils/__tests__/markdown.test.ts
  src/renderer/src/utils/formats.ts
  src/renderer/src/utils/markdown.ts
Labels: kind/test

#6280 fix: assistant emoji displaying incorrectly in specific situations #6243
  src/renderer/src/components/EmojiIcon.tsx
  src/renderer/src/components/EmojiPicker/index.tsx
  src/renderer/src/pages/home/Tabs/components/AssistantItem.tsx
Labels: sig/Assistant

#6738 hotfix: update qwen3 model identification logic to use startsWith for im…
  src/renderer/src/config/models.ts
Labels: hotfix

#6775 fix: prevent message overflow when minimized width
  src/renderer/src/pages/home/Messages/MessageGroup.tsx
Labels: area/UI/UX

#6784 refactor(BackupManager, WebDav): streamline WebDAV client initialization and enhance directory listing functionality
  src/main/services/BackupManager.ts
  src/main/services/WebDav.ts
Labels: kind/cleanup

#6715 feat(SelectionAssistant): Smart Translation ( aka BiDirectionTranslate)
  src/renderer/src/assets/styles/color.scss
  src/renderer/src/config/translate.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/utils/translate.ts
  src/renderer/src/windows/selection/action/SelectionActionApp.tsx
  src/renderer/src/windows/selection/action/components/ActionGeneral.tsx
  src/renderer/src/windows/selection/action/components/ActionTranslate.tsx
  src/renderer/src/windows/selection/action/components/ActionUtils.ts
Labels: area/UI/UX, kind/feature

#6773 fix: codeblock overflow in bubble style
  src/renderer/src/assets/styles/container.scss
  src/renderer/src/assets/styles/markdown.scss
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
  src/renderer/src/components/CodeBlockView/index.tsx
  src/renderer/src/components/CodeEditor/index.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/MessageSelect.tsx
Labels: area/UI/UX

#6675 fix(MermaidPreview): debounce mermaid rendering to alleviate flickering
  src/renderer/src/components/CodeBlockView/MermaidPreview.tsx
Labels: area/Performance

#6810 hotfix: gemini auto thinking
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
Labels: hotfix

#6816 fix: use monospace font for theme colorpicker
  src/renderer/src/context/AntdProvider.tsx
Labels: area/UI/UX

#6813 fix(AnthropicProvider): update usage and metrics handling to prevent TypeError
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
Labels: sig/LLM

#6769 fix: OpenAI provider api check doesn't handle error
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
  src/renderer/src/services/ApiService.ts
Labels: sig/LLM

#6772 feat(Settings): Add token count display toggle
  src/renderer/src/hooks/useSettings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/MessageTokens.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/settings/MCPSettings/InstallNpxUv.tsx
  src/renderer/src/store/settings.ts
Labels: area/UI/UX, kind/feature

#6828 hotfix: ensure show token usage setting defaults to true
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
Labels: hotfix

#5854 refactor: enhance export functions
  src/renderer/src/components/ObsidianExportDialog.tsx
  src/renderer/src/components/Popups/ObsidianExportPopup.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/settings/DataSettings/JoplinSettings.tsx
  src/renderer/src/pages/settings/DataSettings/MarkdownExportSettings.tsx
  src/renderer/src/pages/settings/DataSettings/NotionSettings.tsx
  src/renderer/src/store/settings.ts
  src/renderer/src/utils/export.ts
  src/renderer/src/utils/messageUtils/find.ts
Labels: area/UI/UX, kind/cleanup

#6827 fix: add blank lines between reasoning summary parts
  src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
Labels: area/UI/UX

#6705 support tokenflux image generation for [Flux.1 Kontext]
  src/main/services/AppUpdater.ts
  src/renderer/src/hooks/usePaintings.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/paintings/PaintingsRoutePage.tsx
  src/renderer/src/pages/paintings/TokenFluxPage.tsx
  src/renderer/src/pages/paintings/components/DynamicFormRender.tsx
  src/renderer/src/pages/paintings/config/tokenFluxConfig.ts
  src/renderer/src/pages/paintings/utils/TokenFluxService.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/paintings.ts
  src/renderer/src/types/index.ts
  tokenflux_painting_page.md
Labels: area/UI/UX, kind/feature

#6659 perf: improve responsiveness on streaming formulas
  src/renderer/src/store/thunk/messageThunk.ts
Labels: area/Performance

#6870 hotfix: gemini-2.5-pro-preview-06-05 using error
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
Labels: hotfix

#6869 refactor(SelectionToolbar): add transition effects to action buttons
  src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
Labels: area/UI/UX

#6888 fix(SelectionToolbar): prevent dragging the demo
  src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
Labels: area/UI/UX

#6541 hotfix: enhance OpenAI stream handling and error management
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/utils/stream.ts
Labels: sig/LLM

#6892 refactor: unified image viewer with integrated context menu
  src/main/services/FileService.ts
  src/preload/index.ts
  src/renderer/src/components/ImageViewer.tsx
  src/renderer/src/pages/agents/index.ts
  src/renderer/src/pages/home/Markdown/Markdown.tsx
  src/renderer/src/pages/home/Messages/Blocks/ImageBlock.tsx
  src/renderer/src/pages/paintings/components/Artboard.tsx
Labels: area/UI/UX, kind/cleanup

#6922 feat(restoreFromWebdav): make credentials and path optional
  src/main/services/WebDav.ts
  src/renderer/src/components/WebdavBackupManager.tsx
  src/renderer/src/components/WebdavModals.tsx
  src/renderer/src/pages/settings/DataSettings/WebDavSettings.tsx
  src/renderer/src/services/BackupService.ts
  src/renderer/src/types/index.ts
Labels: sig/Data, kind/feature

#6960 fix: update default translate model to deepseek-v3
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
Labels: sig/LLM

#6971 增加自动更新文档中版本号的github workflow
  .github/workflows/release.yml
Labels: area/CI/CD

#6919 fix: prevent emoji picker from closing unexpectedly with IME
  src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
Labels: area/UI/UX

#6991 feat: add prompt variables description
  src/preload/index.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
Labels: kind/feature

#7017 fix: add Youdao and Nomic logos to model logo mapping
  src/renderer/src/assets/images/providers/netease-youdao.svg
  src/renderer/src/assets/images/providers/nomic.png
  src/renderer/src/config/models.ts
Labels: area/UI/UX

#6995 feat: enhance unresponsive renderer handling and crash reporting
  src/main/index.ts
  src/main/services/WindowService.ts
Labels: kind/feature

#6877 refactor: use CodeEditor for customizing css
  src/renderer/src/components/CodeEditor/index.tsx
  src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
Labels: area/UI/UX, kind/cleanup

#7022 fix: shouldn't edit embedding dimension on existing knowledge base
  src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
  src/renderer/src/providers/AiProvider/BaseProvider.ts
Labels: sig/RAG

#7052 feat: add citation index to show
  src/renderer/src/pages/home/Messages/CitationsList.tsx
Labels: area/UI/UX, kind/feature

#7064 feat(i18n): add tooltips for model name in multiple languages
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
Labels: area/UI/UX, kind/feature

#6999 fix(SelectionAssistant): improve auto-scroll behavior in action window
  src/renderer/src/windows/selection/action/SelectionActionApp.tsx
Labels: area/UI/UX

#6983 feat(SelectionAssistant): shortcut key to toggle on/off
  src/main/services/SelectionService.ts
  src/main/services/ShortcutService.ts
  src/main/services/StoreSyncService.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/ShortcutSettings.tsx
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/shortcuts.ts
Labels: area/UI/UX, kind/feature

#5965 feat: add plain text copy functionality for messages and topics. 添加了复制纯文本的功能（去除Markdown格式符号）
  package.json
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/types/index.ts
  src/renderer/src/utils/__tests__/export.test.ts
  src/renderer/src/utils/__tests__/markdown.test.ts
  src/renderer/src/utils/copy.ts
  src/renderer/src/utils/export.ts
  src/renderer/src/utils/markdown.ts
  yarn.lock
Labels: area/UI/UX, kind/feature

#7044 Feat/support 302ai provider
  src/renderer/src/assets/images/providers/302ai.png
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
Labels: kind/feature, sig/LLM

#7019 feat(Markdown): customize table to support source copying
  src/renderer/src/pages/home/Markdown/Markdown.tsx
  src/renderer/src/pages/home/Markdown/Table.tsx
  src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
  src/renderer/src/pages/home/Markdown/__tests__/Table.test.tsx
  src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Markdown.test.tsx.snap
  src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Table.test.tsx.snap
  src/renderer/src/pages/home/Messages/ChatNavigation.tsx
Labels: area/UI/UX, kind/feature

#6794 feat: animate topic renaming
  src/renderer/src/hooks/useTopic.ts
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/store/runtime.ts
Labels: area/UI/UX, kind/feature

#7116 feat: Support reasoning control for Doubao/Mistral models.
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/assets/images/models/gpt_image_1.png
  src/renderer/src/config/models.ts
  src/renderer/src/pages/home/Inputbar/ThinkingButton.tsx
  src/renderer/src/types/sdk.ts
Labels: kind/feature, sig/LLM

#7115 feat: Optimize assistant drag-and-drop effect
  src/renderer/src/components/DragableList/index.tsx
  src/renderer/src/hooks/useTags.ts
  src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
Labels: area/UI/UX, kind/feature

#7135 feat: Enhance AppUpdater for Windows installation directory support
  src/main/services/AppUpdater.ts
Labels: kind/feature

#7058 fix(MermaidPreview): re-render mermaid on display change
  src/renderer/src/components/CodeBlockView/MermaidPreview.tsx
  src/renderer/src/components/__tests__/MermaidPreview.test.tsx
Labels: area/UI/UX

#7133 feat: clean up Windows license files
  scripts/after-pack.js
Labels: kind/cleanup, area/Performance

#7185 fix(SelectionAssistant): make add custom action button bigger
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/SelectionAssistantSettings/components/SettingsActionsListHeader.tsx
Labels: area/UI/UX

#7189 fix: transparent background on translate dropdown
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
Labels: area/UI/UX

#7191 fix: remove margin-bottom for loading animation
  src/renderer/src/assets/styles/index.scss
Labels: area/UI/UX

#7175 feat: add prompt variables docs on topic naming modal popup
  src/renderer/src/pages/settings/ModelSettings/TopicNamingModalPopup.tsx
Labels: kind/documentation, kind/feature

#6934 fix: send message shortcut doesn't work when editing existing message
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/MessageEditor.tsx
Labels: area/UI/UX

#7211 refactor: Encapsulate image display related components
  src/renderer/src/pages/files/FileList.tsx
  src/renderer/src/pages/files/ImageItem.tsx
  src/renderer/src/pages/files/ImageList.tsx
Labels: area/UI/UX, kind/cleanup

#7212 fix: prevent update button from rendering when auto-check for updates…
  src/renderer/src/pages/home/components/UpdateAppButton.tsx
Labels: area/UI/UX

#7170 refactor(Navbar&Sidebar): rearrange navbar icons, add search functionality for assistants and topics
  src/renderer/src/components/Icons/NarrowModeIcon.tsx
  src/renderer/src/components/Icons/PanelIcons.tsx
  src/renderer/src/pages/home/ChatNavbar.tsx
  src/renderer/src/pages/home/MainSidebar/MainNavbar.tsx
  src/renderer/src/pages/home/MainSidebar/MainSidebar.tsx
  src/renderer/src/pages/home/MainSidebar/SidebarSearch.tsx
  src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/utils/search.ts
Labels: area/UI/UX, kind/cleanup

#7276 fix: unified the behavior of SendMessage shortcut
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/MessageEditor.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/store/settings.ts
  src/renderer/src/utils/input.ts
Labels: area/UI/UX

#7250 fix: add Markdown preview option in translation settings
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/translate/TranslatePage.tsx
Labels: area/UI/UX

#7287 fix: classify agents as Chinese and English
  resources/data/agents-en.json
  resources/data/agents-zh.json
  src/renderer/src/pages/agents/components/AgentGroupIcon.tsx
  src/renderer/src/pages/agents/index.ts
Labels: kind/feature

#7286 feat: toggle Selection Assistant on tray menu
  src/main/services/TrayService.ts
Labels: area/UI/UX, kind/feature

#6096 feat: Add app data path selection and relaunch functionality
  packages/shared/IpcChannel.ts
  src/main/config.ts
  src/main/index.ts
  src/main/ipc.ts
  src/main/services/BackupManager.ts
  src/main/services/KnowledgeService.ts
  src/main/utils/file.ts
  src/preload/index.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
Labels: area/UI/UX, kind/feature

#7323 feat: update gemini-2.5 model capabilities and thinking budget
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/config/models.ts
Labels: kind/feature, sig/LLM

#7342 fix: 修复多模型回答的锚点点击无法跳转问题
  src/renderer/src/pages/home/Messages/MessageAnchorLine.tsx
Labels: area/UI/UX

#7340 fix(ApiService): improve error handling when fetching tools from MCP servers
  src/renderer/src/services/ApiService.ts
Labels: area/Connectivity

#7339 refactor: remove deprecated MCP server handling and knowledge base ID logic from Inputbar and related services
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/services/ApiService.ts
  src/renderer/src/services/MessagesService.ts
  src/renderer/src/types/newMessage.ts
  src/renderer/src/utils/messageUtils/find.ts
Labels: kind/cleanup

#7192 refactor(CodeBlock): support more file extensions for code downloading
  electron.vite.config.ts
  package.json
  src/renderer/src/components/CodeBlockView/index.tsx
  src/renderer/src/utils/__tests__/markdown.test.ts
  src/renderer/src/utils/markdown.ts
  yarn.lock
Labels: kind/cleanup

#7360 refactor: hard-coded language map
  package.json
  packages/shared/config/languages.ts
  src/renderer/src/utils/__tests__/markdown.test.ts
  src/renderer/src/utils/markdown.ts
  yarn.lock
Labels: kind/cleanup

#7363 refactor(Select): provide consistent search experience for antd Select
  src/renderer/src/components/CustomSelect.tsx
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
Labels: area/UI/UX, kind/cleanup

#7288 feat(Markdown): disable indented code blocks
  package.json
  src/renderer/src/components/MarkdownEditor/index.tsx
  src/renderer/src/pages/agents/AgentsPage.tsx
  src/renderer/src/pages/home/Markdown/Markdown.tsx
  src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
  src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Markdown.test.tsx.snap
  src/renderer/src/pages/home/Markdown/plugins/__tests__/disableIndentedCode.test.tsx
  src/renderer/src/pages/home/Markdown/plugins/__tests__/remarkDisableConstructs.test.ts
  src/renderer/src/pages/home/Markdown/plugins/remarkDisableConstructs.ts
  src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
  yarn.lock
Labels: area/UI/UX, kind/feature

#7371 fix(AssistantService): add default settings configuration to assistant initialization
  src/renderer/src/services/AssistantService.ts
Labels: sig/Assistant

#7406 fix: remove duplicated deepseek-v3 in volcengine
  src/renderer/src/config/models.ts
Labels: kind/cleanup

#7407 refactor(middleware): Add error property to CompletionResult and handle errors when checking API
  src/renderer/src/aiCore/middleware/common/ErrorHandlerMiddleware.ts
  src/renderer/src/aiCore/middleware/schemas.ts
  src/renderer/src/services/ApiService.ts
Labels: kind/cleanup

#7374 feat(FileStorage): add support for .doc files using word-extractor
  package.json
  packages/shared/config/constant.ts
  src/main/loader/index.ts
  src/main/services/FileStorage.ts
  src/main/utils/__tests__/file.test.ts
  yarn.lock
Labels: kind/feature

#7358 fix(Markdown): improve latex brackets handling
  package.json
  src/renderer/src/pages/home/Markdown/Markdown.tsx
  src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
  src/renderer/src/utils/__tests__/formats.test.ts
  src/renderer/src/utils/__tests__/markdown.test.ts
  src/renderer/src/utils/formats.ts
  src/renderer/src/utils/markdown.ts
  yarn.lock
Labels: area/UI/UX

#7465 feat(mcpServers): Add a thought field to sequential thinking mcp server
  src/main/mcpServers/sequentialthinking.ts
Labels: sig/MCP, kind/feature

#7413 refactor: file actions into FileAction service
  src/renderer/src/pages/files/FileList.tsx
  src/renderer/src/pages/files/FilesPage.tsx
  src/renderer/src/services/FileAction.ts
Labels: area/UI/UX, kind/cleanup

#7506 feat: implement Python MCP server using existing Pyodide infrastructure
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/mcpServers/factory.ts
  src/main/mcpServers/python.ts
  src/main/services/PythonService.ts
  src/preload/index.ts
  src/renderer/src/services/PyodideService.ts
  src/renderer/src/store/mcp.ts
Labels: sig/MCP, kind/feature

#7531 feat: Support custom registry address when configuring mcp for npm & fix lint error
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: sig/MCP, kind/feature

#7511 refactor(GeminiAPIClient): separate model and user message handling to adapt vertex
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/aiCore/middleware/core/McpToolChunkMiddleware.ts
Labels: kind/cleanup

#7534 feat(SelectionAssistant): actionWindow show footer a while when initial showing and key pressing
  src/renderer/src/windows/selection/action/components/WindowFooter.tsx
Labels: area/UI/UX, kind/feature

#7537 fix(SelectionAssistant): opacity slider too slow when sliding in settings page
  src/renderer/src/pages/settings/SelectionAssistantSettings/SelectionAssistantSettings.tsx
Labels: area/UI/UX

#7532 refactor(SelectionAssistant): make all Toolbar CSS variables customizable
  src/renderer/selectionToolbar.html
  src/renderer/src/assets/styles/selection-toolbar.scss
  src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
Labels: area/UI/UX, kind/cleanup

#7409 refactor(CodePreview): handle chunking in ShikiStreamService, make the algorithm more robust
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
  src/renderer/src/context/CodeStyleProvider.tsx
  src/renderer/src/services/ShikiStreamService.ts
Labels: kind/cleanup

#7539 feat(MentionedModels): improve feedback for MessageGroupModelList
  src/renderer/src/pages/home/Messages/MessageGroupModelList.tsx
  src/renderer/src/utils/motionVariants.ts
Labels: area/UI/UX

#7568 feat(FileStorage): enhance open dialog to handle large files by retur…
  src/main/services/FileStorage.ts
Labels: area/Performance

#7600 fix(Selector): Fix the issue with the Selector component being selected.
  src/renderer/src/components/Selector.tsx
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
Labels: area/UI/UX

#7587 refactor: show error on missing mcp tool
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/utils/mcp-tools.ts
Labels: sig/MCP

#7588 refactor(CodePreview): line numbers as elements
  src/renderer/src/components/CodeBlockView/CodePreview.tsx
Labels: kind/cleanup

#7611 docs: add 20 language links of README
  README.md
Labels: kind/documentation

#7439 feat: Increase the upper limit of web search results
  src/renderer/src/pages/settings/WebSearchSettings/BasicSettings.tsx
Labels: area/UI/UX, kind/feature

#7628 fix: move ContentSearch below Messages in Chat layout
  src/renderer/src/pages/home/Chat.tsx
Labels: area/UI/UX

#7624 fix(models): update regex patterns for Doubao models and enhance function checks
  src/renderer/src/config/models.ts
Labels: kind/cleanup

#7635 fix(Menubar): icon for multi select
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
Labels: area/UI/UX

#7493 ♻️ refactor(ContentSearch): ContentSearch to use CSS highlights API
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/components/ContentSearch.tsx
  src/renderer/src/pages/home/Chat.tsx
Labels: area/UI/UX, kind/cleanup

#6802 feat: Add S3 Backup
  package.json
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/BackupManager.ts
  src/main/services/RemoteStorage.ts
  src/preload/index.ts
  src/renderer/src/components/S3BackupManager.tsx
  src/renderer/src/components/S3Modals.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/init.ts
  src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
  src/renderer/src/pages/settings/DataSettings/S3Settings.tsx
  src/renderer/src/services/BackupService.ts
  src/renderer/src/store/backup.ts
  src/renderer/src/store/settings.ts
  src/renderer/src/types/index.ts
  yarn.lock
Labels: sig/Data, kind/feature

#7644 chore: format zh-cn and zh-tw i18n strings with pangu.
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
Labels: kind/cleanup

#7656 Improvement/memory UI
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/memory/MemoryService.ts
  src/main/services/memory/queries.ts
  src/preload/index.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/memory/index.tsx
  src/renderer/src/pages/memory/settings-modal.tsx
  src/renderer/src/services/MemoryService.ts
Labels: area/UI/UX

#7652 feat: support linux deb
  electron-builder.yml
Labels: kind/feature

#7632 fix: textarea not resizing back after clearing long input (#7609)
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: area/UI/UX

#7567 Feat/ppio rerank
  src/renderer/src/aiCore/clients/ApiClientFactory.ts
  src/renderer/src/aiCore/clients/ppio/PPIOAPIClient.ts
  src/renderer/src/config/models.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
Labels: kind/feature, sig/LLM

#7683 style(antd): Optimize antd components through patch method
  .yarn/patches/antd-npm-5.24.7-356a553ae5.patch
  package.json
  src/renderer/src/assets/styles/index.scss
  src/renderer/src/context/AntdProvider.tsx
  src/renderer/src/pages/agents/components/AddAgentPopup.tsx
  src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
  src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantKnowledgeBaseSettings.tsx
  src/renderer/src/pages/settings/AssistantSettings/AssistantModelSettings.tsx
  src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelEditContent.tsx
  src/renderer/src/pages/settings/WebSearchSettings/CompressionSettings/CutoffSettings.tsx
  src/renderer/src/pages/settings/WebSearchSettings/CompressionSettings/RagSettings.tsx
  src/renderer/src/pages/settings/WebSearchSettings/CompressionSettings/index.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
  yarn.lock
Labels: area/UI/UX
