Repository CherryHQ/cherry-studio, pull requests merged in 2025-08, with the labels that each got.

#8756 fix(Inputbar): input bar auto focus
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: needs-review

#7794 feat(ProviderSettings): add more api options for non-system providers
  scripts/auto-translate-i18n.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/hooks/useProvider.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/ProviderSettings/AddProviderPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ApiOptionsSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSettingsPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/match.ts
  src/renderer/src/utils/naming.ts
Labels: needs-review

#8253 feat: add OpenAI o3 model support with enhanced tool calling
  AGENT.md
  CLAUDE.md
  resources/data/agents-zh.json
  src/main/services/ProxyManager.ts
  src/renderer/src/utils/__tests__/mcp-schema.test.ts
  src/renderer/src/utils/mcp-schema.ts
  src/renderer/src/utils/mcp-tools.ts
Labels: needs-review, PM said OK

#8901 fix(settings): reading undefined caused crash
  src/renderer/src/hooks/useProvider.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
Labels: needs-review

#8906 fix: drag providers caused crash
  src/renderer/src/components/DraggableList/virtual-list.tsx
  src/renderer/src/components/__tests__/__snapshots__/DraggableVirtualList.test.tsx.snap
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
Labels: needs-review

#8903 fix(mcp): builtin mcp objects cannot be serialized
  src/renderer/src/i18n/label.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/MCPSettings/BuiltinMCPServersSection.tsx
  src/renderer/src/store/mcp.ts
  src/renderer/src/types/index.ts
Labels: needs-review

#8888 feat: more control for service tier
  .yarn/patches/openai-npm-5.1.0-0e7b3ccb07.patch
  .yarn/patches/openai-npm-5.12.0-a06a6369b2.patch
  package.json
  src/renderer/src/aiCore/clients/BaseApiClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/hooks/useProvider.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/pages/home/Tabs/components/OpenAISettingsGroup.tsx
  src/renderer/src/pages/settings/ProviderSettings/ApiOptionsSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/AwsBedrockSettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/ModelList/ModelList.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderOAuth.tsx
  src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
  src/renderer/src/pages/settings/ProviderSettings/VertexAISettings.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/services/__tests__/ApiService.test.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
  src/renderer/src/types/index.ts
  src/renderer/src/utils/__tests__/match.test.ts
  src/renderer/src/utils/__tests__/naming.test.ts
  src/renderer/src/utils/match.ts
  src/renderer/src/utils/naming.ts
  yarn.lock
Labels: needs-review

#8731 feat(knowledge): add save topic to knowledge
  src/renderer/src/components/Popups/SaveToKnowledgePopup.tsx
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/utils/__tests__/topicKnowledge.test.ts
  src/renderer/src/utils/knowledge.ts
Labels: needs-review

#8907 fix: user custom params should always overwrite other params
  src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
  src/renderer/src/aiCore/clients/aws/AwsBedrockAPIClient.ts
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
  src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
Labels: needs-review

#9200 fix: unexpected quitting full screen mode
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/WindowService.ts
  src/preload/index.ts
  src/renderer/src/components/CollapsibleSearchBar.tsx
  src/renderer/src/components/ContentSearch.tsx
  src/renderer/src/components/EditableNumber/index.tsx
  src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
  src/renderer/src/components/QuickPanel/view.tsx
  src/renderer/src/components/TopView/index.tsx
  src/renderer/src/hooks/useInPlaceEdit.ts
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/InputbarTools.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
Labels: needs-review

#9409 feat: Image OCR
  .yarn/patches/tesseract.js-npm-6.0.1-2562a7e46d.patch
  package.json
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/ocr/OcrService.ts
  src/main/services/ocr/tesseract/TesseractService.ts
  src/main/utils/ocr.ts
  src/preload/index.ts
  src/renderer/src/assets/images/providers/Tesseract.js.png
  src/renderer/src/config/ocr.ts
  src/renderer/src/config/ocrProviders.ts
  src/renderer/src/hooks/useOcr.ts
  src/renderer/src/hooks/useOcrProvider.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/DocProcessSettings/OcrImageSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrProviderSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrTesseractSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/PreprocessProviderSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/PreprocessSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/index.tsx
  src/renderer/src/pages/settings/SettingsPage.tsx
  src/renderer/src/services/ocr/OcrService.ts
  src/renderer/src/services/ocr/clients/OcrApiClientFactory.ts
  src/renderer/src/services/ocr/clients/OcrBaseApiClient.ts
  src/renderer/src/services/ocr/clients/OcrExampleApiClient.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/ocr.ts
  src/renderer/src/types/file.ts
  src/renderer/src/types/index.ts
  src/renderer/src/types/ocr.ts
  src/renderer/src/utils/ocr.ts
  yarn.lock
Labels: needs-review

#9423 feat: ocr image to translate
  packages/shared/IpcChannel.ts
  src/main/ipc.ts
  src/main/services/FileSystemService.ts
  src/main/utils/file.ts
  src/preload/index.ts
  src/renderer/src/components/TopView/index.tsx
  src/renderer/src/hooks/useDrag.ts
  src/renderer/src/hooks/useFiles.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/home/Inputbar/AttachmentButton.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
  src/renderer/src/services/PasteService.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/translate.ts
  src/renderer/src/utils/file.ts
Labels: needs-review, Blocked

#9361 fix: restrict using gemini native tools and mcp tools simultaneously
  src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
  src/renderer/src/config/models.ts
  src/renderer/src/config/providers.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/home/Inputbar/InputbarTools.tsx
  src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
  src/renderer/src/pages/home/Inputbar/UrlContextbutton.tsx
  src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
  src/renderer/src/utils/__tests__/assistant.test.ts
  src/renderer/src/utils/assistant.ts
  src/renderer/src/utils/mcp-tools.ts
Labels: needs-review

#9267 feat: more abort control
  src/renderer/src/aiCore/index.ts
  src/renderer/src/aiCore/middleware/common/AbortHandlerMiddleware.ts
  src/renderer/src/aiCore/middleware/schemas.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/translate/TranslatePage.tsx
  src/renderer/src/services/ApiService.ts
  src/renderer/src/services/TranslateService.ts
  src/renderer/src/store/runtime.ts
Labels: needs-review

#9572 feat: System (MacOS & Windows) OCR
  package.json
  src/main/services/ocr/OcrService.ts
  src/main/services/ocr/builtin/OcrBaseService.ts
  src/main/services/ocr/builtin/SystemOcrService.ts
  src/main/services/ocr/builtin/TesseractService.ts
  src/main/services/ocr/tesseract/TesseractService.ts
  src/main/utils/ocr.ts
  src/renderer/src/components/InfoPopover.tsx
  src/renderer/src/components/Tags/ErrorTag.tsx
  src/renderer/src/components/Tags/SuccessTag.tsx
  src/renderer/src/components/Tags/WarnTag.tsx
  src/renderer/src/config/ocr.ts
  src/renderer/src/hooks/useDrag.ts
  src/renderer/src/hooks/useOcr.ts
  src/renderer/src/hooks/useOcrProvider.ts
  src/renderer/src/hooks/useOcrProvider.tsx
  src/renderer/src/i18n/label.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/i18n/translate/el-gr.json
  src/renderer/src/i18n/translate/es-es.json
  src/renderer/src/i18n/translate/fr-fr.json
  src/renderer/src/i18n/translate/pt-pt.json
  src/renderer/src/pages/settings/DocProcessSettings/OcrImageSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrProviderSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrSystemSettings.tsx
  src/renderer/src/pages/settings/DocProcessSettings/OcrTesseractSettings.tsx
  src/renderer/src/pages/translate/TranslatePage.tsx
  src/renderer/src/services/ocr/OcrService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/ocr.ts
  src/renderer/src/types/file.ts
  src/renderer/src/types/index.ts
  src/renderer/src/types/ocr.ts
  src/renderer/src/utils/file.ts
  src/renderer/src/utils/ocr.ts
  yarn.lock
Labels: needs-review

#9663 fix: cloudflare turnstile protection error
  src/main/services/WebviewService.ts
Labels: needs-review
