Repository CherryHQ/cherry-studio, pull requests merged in 2025-04, with the labels that each got.

#3773 refactor(Constants): 优化一些常量和枚举值
  packages/shared/IpcChannel.ts
  packages/shared/config/constant.ts
  src/main/index.ts
  src/main/ipc.ts
  src/main/services/AppUpdater.ts
  src/main/services/BackupManager.ts
  src/main/services/ConfigManager.ts
  src/main/services/FileStorage.ts
  src/main/services/KnowledgeService.ts
  src/main/services/ReduxService.ts
  src/main/services/WindowService.ts
  src/preload/index.ts
  src/renderer/src/components/Popups/BackupPopup.tsx
  src/renderer/src/components/Popups/RestorePopup.tsx
  src/renderer/src/context/ThemeProvider.tsx
  src/renderer/src/hooks/useAppInit.ts
  src/renderer/src/hooks/useFullScreenNotice.ts
  src/renderer/src/hooks/useKnowledge.ts
  src/renderer/src/hooks/useMCPServers.ts
  src/renderer/src/hooks/useUpdateHandler.ts
  src/renderer/src/i18n/index.ts
  src/renderer/src/pages/files/GeminiFiles.tsx
  src/renderer/src/pages/settings/GeneralSettings.tsx
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/store/llm.ts
  src/renderer/src/store/settings.ts
  src/renderer/src/utils/index.ts
  src/renderer/src/windows/mini/home/HomeWindow.tsx
Labels: needs-review

#4356 feat(QuickPanel): Add new feature QuickPanel, unify input box operation.
  src/renderer/src/components/CustomCollapse.tsx
  src/renderer/src/components/QuickPanel/hook.ts
  src/renderer/src/components/QuickPanel/index.ts
  src/renderer/src/components/QuickPanel/provider.tsx
  src/renderer/src/components/QuickPanel/types.ts
  src/renderer/src/components/QuickPanel/view.tsx
  src/renderer/src/databases/index.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/files/FileList.tsx
  src/renderer/src/pages/home/Chat.tsx
  src/renderer/src/pages/home/Inputbar/AttachmentButton.tsx
  src/renderer/src/pages/home/Inputbar/AttachmentPreview.tsx
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Inputbar/KnowledgeBaseButton.tsx
  src/renderer/src/pages/home/Inputbar/KnowledgeBaseInput.tsx
  src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
  src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
  src/renderer/src/pages/home/Inputbar/MentionModelsInput.tsx
  src/renderer/src/pages/home/Inputbar/QuickPhrasesButton.tsx
  src/renderer/src/pages/home/Messages/NarrowLayout.tsx
  src/renderer/src/pages/settings/QuickPhraseSettings/index.tsx
  src/renderer/src/pages/settings/SettingsPage.tsx
  src/renderer/src/services/QuickPhraseService.ts
  src/renderer/src/types/index.ts
Labels: wip

#4167 perf(CodeBlock): improve long codeblock loading experience
  package.json
  src/renderer/src/context/SyntaxHighlighterProvider.tsx
  src/renderer/src/hooks/useMermaid.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Markdown/CodeBlock.tsx
  src/renderer/src/pages/home/Tabs/SettingsTab.tsx
  src/renderer/src/services/CodeCacheService.ts
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
  yarn.lock
Labels: needs-review, wip

#3431 Add support for Windows ARM64 platform
  .github/workflows/nightly-build.yml
  .github/workflows/release.yml
  .yarn/patches/libsql-npm-0.4.7-444e260fb1.patch
  electron-builder.yml
  package.json
  scripts/after-pack.js
  scripts/build-npm.js
  scripts/utils.js
  yarn.lock
Labels: needs-review

#4593 fix: missing ExportMenuOptions in persist leads to useSelector re-render a lot
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
  src/renderer/src/pages/settings/DataSettings/ExportMenuSettings.tsx
  src/renderer/src/store/index.ts
  src/renderer/src/store/migrate.ts
  src/renderer/src/store/settings.ts
Labels: P1

#4496 fix: 解决聊天页面图片复制失败的问题和点击编辑回复的时候，不显示图片url的问题
  src/renderer/src/pages/home/Messages/MessageImage.tsx
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
Labels: needs-review

#4408 feat: add model provider logo upload
  src/renderer/src/components/Popups/UserPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/AddProviderPopup.tsx
  src/renderer/src/pages/settings/ProviderSettings/index.tsx
  src/renderer/src/services/ImageStorage.ts
Labels: needs-review

#4812 feat(model): add ModelCard schema and related types for input/output capabilities
  src/renderer/src/types/model.ts
Labels: needs-review

#4285 feat(MessageContent): Add Collapsible Citations Display
  package.json
  src/renderer/src/pages/home/Messages/CitationsList.tsx
  src/renderer/src/pages/home/Messages/Message.tsx
  src/renderer/src/pages/home/Messages/MessageContent.tsx
  yarn.lock
Labels: needs-review

#4620 feat: add chat message translate copy button
  src/renderer/src/hooks/useMessageOperations.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
  src/renderer/src/pages/home/Messages/MessageMenubar.tsx
Labels: needs-review

#5314 Update issue-management.yml
  .github/ISSUE_TEMPLATE/#2_question.yml
  .github/ISSUE_TEMPLATE/#3_others.yml
  .github/ISSUE_TEMPLATE/2_question.yml
  .github/ISSUE_TEMPLATE/3_others.yml
  .github/issue-checker.yml
  .github/workflows/issue-checker.yml
  .github/workflows/issue-management.yml
Labels: needs-review

#5349 feat(models): add new search models
  src/renderer/src/config/models.ts
Labels: kind/documentation, Dev Team, area/UI/UX

#5351 Add MCP server installation via URL protocol
  packages/shared/IpcChannel.ts
  src/main/services/ProtocolClient.ts
  src/main/services/urlschema/mcp-install.ts
  src/renderer/src/env.d.ts
  src/renderer/src/hooks/useMCPServers.ts
  src/renderer/src/services/NavigationService.ts
Labels: kind/documentation, client:win, Dev Team, sig/MCP, area/UI/UX

#5360 feat: Implement deep linking for AppImage on Linux
  electron-builder.yml
  src/main/index.ts
  src/main/services/ProtocolClient.ts
Labels: kind/documentation, client:win, client:linux, area/UI/UX

#5347 fix: more robust portable data dir setup logic
  src/main/index.ts
  src/main/utils/file.ts
Labels: client:mac, client:win, client:linux

#5364 feat: Enable image generation in assistant based on model selection
  src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Labels: Dev Team, sig/Assistant

#5374 feat: Enhance theme management with auto mode support
  src/main/ipc.ts
  src/preload/index.d.ts
  src/preload/index.ts
  src/renderer/src/components/app/Sidebar.tsx
  src/renderer/src/context/ThemeProvider.tsx
Labels: kind/documentation, client:win, Dev Team, area/UI/UX

#5379 fix: Fix the image support for the GitHub Copilot models
  src/renderer/src/config/models.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Labels: kind/documentation, area/UI/UX, sig/LLM

#5384 fix(MCPSettings): fix mcp setting state error,fix mcp setting save searchKey lose
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: kind/documentation, client:win, sig/MCP, area/UI/UX

#5386 Feat/mcp enhancement
  src/main/services/MCPService.ts
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
  src/renderer/src/pages/settings/MCPSettings/modelscopeSyncUtils.ts
  src/renderer/src/store/mcp.ts
  src/renderer/src/types/index.ts
Labels: kind/documentation, client:win, Dev Team, sig/MCP, area/UI/UX

#5393 feat(MCPService): add method to find PowerShell executable path
  src/main/services/MCPService.ts
Labels: kind/documentation, client:win, Dev Team, sig/MCP, area/UI/UX

#5394 Add MCP resources dropdown in settings navbar
  src/renderer/src/pages/settings/MCPSettings/McpSettingsNavbar.tsx
Labels: kind/documentation, client:win, Dev Team, sig/MCP, area/UI/UX

#5397 fix(OpenAIProvider): refine system message handling for specific model IDs
  src/renderer/src/config/models.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Labels: sig/LLM

#5408 chore: add grok image alias
  src/renderer/src/config/models.ts
Labels: kind/documentation, client:win, Dev Team, area/UI/UX

#5389 #4288 Added a "Copy" button next to each search result.
  src/renderer/src/pages/knowledge/components/KnowledgeSearchPopup.tsx
Labels: kind/documentation, client:win, area/UI/UX

#5416 fix: update electron-updater patch and refine content-type regex
  .yarn/patches/electron-updater-npm-6.6.3-9269dbaf84.patch
  yarn.lock
Labels: kind/documentation, client:win, Dev Team, area/UI/UX

#5417 fix(AppUpdater): update condition for checking available updates
  src/main/services/AppUpdater.ts
Labels: kind/documentation, client:win, Dev Team, area/UI/UX

#5412 refactor: simplify window.api definition
  src/preload/index.d.ts
  src/preload/index.ts
  src/preload/preload.d.ts
  src/renderer/src/store/shortcuts.ts
  tsconfig.web.json
Labels: client:win, Dev Team

#5411 fix(MCPService): Tool call failure caused by incorrect tool parameters
  src/main/services/MCPService.ts
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: client:win, sig/MCP, area/UI/UX

#5438 style: optimize mcp arg name display layout
  src/renderer/src/pages/settings/MCPSettings/McpPrompt.tsx
  src/renderer/src/pages/settings/MCPSettings/McpTool.tsx
Labels: sig/MCP, area/UI/UX, lgtm, size:XS

#5434 chore: Update runtime version in VSCode launch configuration
  .vscode/launch.json
Labels: lgtm

#5449 fix(McpOAuthClientProvider): update redirect URL
  src/main/services/mcp/oauth/callback.ts
  src/main/services/mcp/oauth/provider.ts
Labels: sig/MCP, lgtm, size:XS

#5450 feat: 允许功能键(F1-F19)可以被设置为快捷键而不需要修饰键
  src/renderer/src/pages/settings/ShortcutSettings.tsx
Labels: kind/feature, size:XS

#5453 refactor: use the existing hook
  src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Labels: sig/MCP, kind/cleanup, size:XS

#5447 fix(GeminiProvider): enhance image generation logic and response configuration
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
Labels: size:S

#5459 refactor(TopicsTab): Use onContextMenu instead of onMouseEnter
  src/renderer/src/pages/home/Tabs/TopicsTab.tsx
Labels: kind/cleanup, size:XS

#5476 feat: 添加 messageBlock、messageThunk 和 useMessageOperations 使用指南文档
  docs/technical/how-to-use-messageBlock.md
  docs/technical/how-to-use-messageThunk.md
  docs/technical/how-to-use-useMessageOperations.md
Labels: kind/documentation

#5483 refactor(MainTextBlock): enhance content processing by ignoring tooluse
  src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Labels: kind/cleanup

#5489 perf: <tool_use> display
  src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
  src/renderer/src/services/StreamProcessingService.ts
Labels: area/Performance

#5470 feat: optimize extract logic
  src/renderer/src/config/prompts.ts
  src/renderer/src/services/ApiService.ts
  src/renderer/src/utils/extract.ts
Labels: area/Performance

#5504 feat(messageThunk): integrate autoRenameTopic functionality to update topic names based on assistant responses
  src/renderer/src/store/thunk/messageThunk.ts
Labels: sig/Assistant, kind/feature

#5509 fix: determining thinking process using block status
  src/renderer/src/i18n/locales/en-us.json
  src/renderer/src/i18n/locales/ja-jp.json
  src/renderer/src/i18n/locales/ru-ru.json
  src/renderer/src/i18n/locales/zh-cn.json
  src/renderer/src/i18n/locales/zh-tw.json
  src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
  src/renderer/src/pages/home/Messages/MessageThought.tsx
Labels: area/UI/UX

#5467 style: optimize mcp arg name display layout when tool or prompt descr…
  src/renderer/src/pages/settings/MCPSettings/McpPrompt.tsx
  src/renderer/src/pages/settings/MCPSettings/McpTool.tsx
Labels: sig/MCP, area/UI/UX, size:M

#5532 feat(WindowService): add main window monitor for renderer process events
  src/main/services/WindowService.ts
Labels: kind/feature

#5546 feat: support streaming for model health check
  src/renderer/src/providers/AiProvider/AnthropicProvider.ts
  src/renderer/src/providers/AiProvider/BaseProvider.ts
  src/renderer/src/providers/AiProvider/GeminiProvider.ts
  src/renderer/src/providers/AiProvider/OpenAIProvider.ts
  src/renderer/src/providers/AiProvider/index.ts
  src/renderer/src/services/ModelService.ts
Labels: kind/feature, sig/LLM
